### ISSUE TITLE
Selected SAL type not reflected on MFD

### ISSUE THREAD

**Issue by sevn10** [AH-64D-Apache-Official-Project/AH-64D#17]
When SAL 1 and 2's are equipped the MFD does not update to display when SAL 1's are selected, it remains stuck on SAL 2.

**Comment by Ollieollieolllie** [comment]
i could not replicate this issue the only issue i could see was that radar missile was showing as sal 2 the others changed to what they were intended

**Comment by sevn10** [comment]
Yeah, it's only that radar missiles are not showing as SAL 1. I tried the default loadout and making a custom one of only AGM-114L's and the MFD still only said SAL 2.

**Comment by Ollieollieolllie** [comment]
Issue being that this bug is intentional to the fact that when added there was no icon for RF so was intentionally left as sal 2

**Comment by mattysmith22** [comment]
Apparently according to the manual there is one for `RF`. In order to add it though I'll require some texturing done.

For anyone willing to do the work, it'll need to be in the same dimensions and scale as [this](https://github.com/AH-64D-Apache-Official-Project/AH-64D/blob/master/%40AH-64D%20Apache%20Longbow/Addons/fza_ah64_us/tex/ICONS/SAL2.paa) and reference material for the icon can be found on page 716 of the publicintelligence manual

**Comment by sevn10** [comment]
![Screenshot 2021-04-01 210911](https://user-images.githubusercontent.com/71986910/113369168-9b681380-932e-11eb-974b-c3918a0ce17f.png)

That RF indicator under type?

**Comment by Ollieollieolllie** [comment]
Fix for this is in ammo rework PR

**Comment by mattysmith22** [comment]
> ![Screenshot 2021-04-01 210911](https://user-images.githubusercontent.com/71986910/113369168-9b681380-932e-11eb-974b-c3918a0ce17f.png)
> 
> That RF indicator under type?

Correct, that is the one

**Comment by mattysmith22** [comment]
> Fix for this is in ammo rework PR

Great, thank you! I have linked this issue to your PR so it will close when it is merged.
