### ISSUE TITLE
Lag & FPS drops when flying over rocks

### ISSUE THREAD

**Issue by Ollieollieolllie** [AH-64D-Apache-Official-Project/AH-64D#30]
in a server environment where fps is low, anything that effect performance affects it big and is more noticeable on server, this bug can cause one to drop from 20fps to 3 fps
Most likely cause
getpos - as it defaults to calculating the altitude above terrain minus the rocks, building above that terrain ( in IHADSS most likely)

**Comment by mattysmith22** [comment]
Good find, I will look for a way to profile the different scripts and see what is causing it.

Could you find a large-ish area for me to hover that causes the lag so I can run scripts while hovering in it?

**Comment by mattysmith22** [comment]
I have found that this issue is not specifically to do with scripts - it happens even when all of them are disabled! We will need to investigate further on what it may be, but there is a chance it is just that rock bunches are particularly laggy - in which case there's nothing we can do!

(without scripts was nulling the entire `schedarray`)

|  | FPS with scripts | FPS without scripts |
| :-- | :--: | :--: |
| Over rocks | 10 | 25 |
| Not over rocks | 50 | 90 |

**Comment by Ollieollieolllie** [comment]
could see if the same event occurs in other aircraft of if its a model or cfg issuie

**Comment by Ollieollieolllie** [comment]
The best way to fix this bug is optimise the shit out of the apache so its not noticeable like it vanilla aircraft
