### ISSUE TITLE
Modern and Near Future Weapons 

### ISSUE THREAD

**Issue by FPFalcon** [AH-64D-Apache-Official-Project/AH-64D#557]
**Aims**
More weapons/ more versatility with the AH-64

**How do you envision this feature being implemented?
New weapons and capabilities 
DAGR, for use with the M299 launcher, 1 launch rail can be equipped with 4 DAGR missiles. each package can be 1 warhead for simplicity.

APKWS, uses the same Hydra-70 rocket pod. Simple to add guided versions of the Hydra-70 rockets to the list.

JAGM: Dual seeker mode Hellfire millimeter wave radar/semi-active laser homing (MMWR/SALH).
Yes it is two seekers in one missile

Recommend for both to limit warhead variants:
DAGR: M151 (HE-FRAG) limited penetration value
Yes Wiki says it's HEDP, but it's HE-FRAG

APKWS is more versatile as the seeker is behind the warhead:
M151/M229 HE-FRAG
M247(HEDP)/M282 MPP(HEAT-FRAG)
M282 is an updated M247 with more payload

JAGM: Just need to combine the guidance system of the AGM-114L and -114K. 

For the models: 
RHS already has the DAGR pods for the little bird. 

APKWS models can be a Hydra-70 whose warhead sticks out past the rocket pod, or use RHS models.

JAGM: Just a HellFire II with a new seeker, dimensions are the same. In fact you can basically copy paste the -114K model, just change the designation to AGM-179.

What modifications need to be made in order to provide the functionality:
Adding these systems would involve adding the targeting system of the hellfire to the new missiles, should be easy for the DAGR. But would require updating the WPS page if APKWS are selected as they take up the rocket pods.

**Reference material**
DAGR
https://www.wearethemighty.com/mighty-tactical/this-is-what-happens-when-you-put-lasers-on-rockets/

APKWS
https://en.m.wikipedia.org/wiki/Advanced_Precision_Kill_Weapon_System

APKWS warheads and JAGM
https://images.app.goo.gl/jP9iepbbv3FdCw8VA

[Thurs_16Nov_1445_kay_3whitehouse (JAMS).pptx.pdf](https://github.com/AH-64D-Apache-Official-Project/AH-64D/files/14909992/Thurs_16Nov_1445_kay_3whitehouse.JAMS.pptx.pdf)

**Comment by Ollieollieolllie** [comment]
Thank you for your request, However, the team will not be implementing any of these items as they were not features of the aircraft being represented in ARMA3. The team has worked extremely hard to present an accurate representation of the AH-64D, Block 1 aircraft within the limitations of ARMA and development time. Additionally, the team’s vision for the AH-64 is an aircraft that has in-built limitations accurate to the aircraft and requires skill and realistic employment of the aircraft to be successfully employed. Furthermore, a lot of the systems being requested would raise a lot of eyebrows due to the sensitive nature of these systems, and the team would like to avoid that.

Best regards
Development Team.
